# Generated by Django 5.1.3 on 2025-02-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_registration_date_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='level',
            field=models.CharField(choices=[('Basic', 'Basic (200,000 Naira)'), ('Intensive', 'Intensive (300,000 Naira)'), ('Advanced', 'Advanced (400,000 Naira)')], default=0.00032921810699588475, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='course',
            field=models.CharField(choices=[('Course 1', 'Course 1'), ('Course 2', 'Course 2'), ('Course 3', 'Course 13')], max_length=50),
        ),
    ]
