# Generated by Django 5.1.3 on 2025-02-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_registration_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='level',
            field=models.CharField(choices=[('Basic', 'Basic (200,000 Naira)'), ('Intensive', 'Intensive (300,000 Naira)'), ('Advanced', 'Advanced (400,000 Naira)')], max_length=50),
        ),
    ]
