# Generated by Django 5.1.3 on 2025-03-07 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_registration_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='level',
        ),
        migrations.AlterField(
            model_name='registration',
            name='course',
            field=models.CharField(choices=[('Basic', 'Basic (200,000 Naira)'), ('Intensive', 'Intensive (300,000 Naira)'), ('Advanced', 'Advanced (400,000 Naira)')], max_length=50),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('Basic', 'Basic (200,000 Naira)'), ('Intensive', 'Intensive (300,000 Naira)'), ('Advanced', 'Advanced (400,000 Naira)')], max_length=50)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paid', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.registration')),
            ],
        ),
    ]
